### ISSUE TITLE
Add equipment descriptions

### ISSUE THREAD

**Issue by Haffi** [kjwise/5thEditionCharacterSheet#16]
Some weapons and other equipment have features that don't fit into the current space, loot can also need more than a title.

**Comment by kjwise** [comment]
So you want extra stuff for the attacks and spellcasting table as well as extra stuff within the equipment list?

What about an extra section with hyperlinks from the attacks and spellcasting / equipment where you could see all the information you have in the json?

**Comment by Haffi** [comment]
The "Attacks" list doesn't need to change, this is more for stuff like
"Decanter of Endless Water" but would also benefit weapons like "Arrow of
the Phoenix".
Very selfish feature request :)
