### ISSUE TITLE
Spell area appears for characters without spells in FF

### ISSUE THREAD

**Issue by bjornlevi** [kjwise/5thEditionCharacterSheet#19]
https://rawgit.com/kjwise/5thEditionCharacterSheet/rewrite/charsheet.html?charURL=https://rawgit.com/kjwise/5thEditionCharacterSheet/rewrite/fireaxe.js

**Comment by kjwise** [comment]
Fixed in https://github.com/kjwise/5thEditionCharacterSheet/commit/c05a7f3701fcd7828ec94ef538e889d42eba5635
